### ISSUE TITLE
SVAR for Raspbian

### ISSUE THREAD

**Issue by Abdula-2015** [Arkq/svar#2] opened 2019-05-05 20:35 UTC
Hello, dear Arkadiusz,

Can your program work on Raspberry PI 3B with Raspbian?

**Comment by Arkq** [comment] 2019-08-17 08:29
It is a standard Linux application, so it should work - compile and try it.
I'm closing this issue because it is not a bug report.

**Closed by Arkq** 2019-08-17 08:29 UTC
